/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "controller_ip": {                               "en": "UniFi-Controller IP/Hostname",                    "de": "UniFi-Controller IP/Hostname",                    "ru": "Унифи-контроллер IP/имя хоста",                   "pt": "UniFi-Controlador IP/Hostname",                   "nl": "UniFi-Controller IP/Hostnaam",                    "fr": "UniFi-Contrôleur IP/nom d'hôte",                  "it": "UniFi-Controller IP/Hostname",                    "es": "UniFi-Controlador IP/nombre de host",             "pl": "Унифи-kontroler IP/nazwa hosta",                  "zh-cn": "统一控制IP/Hostname"},
    "controller_ip_info": {                          "en": "IP address of UniFi-Controller (default: 127.0.0.1)", "de": "Die IP-Adresse der UniFi-Controller (Standardwert: 127.0.0.1)", "ru": "IP-адрес Унифи-контроллер (по умолчанию: 127.0.0.1)", "pt": "Endereço IP do UniFi-Controlador (predefinição: 127.0.0.1)", "nl": "IP-adres van de UniFi-Controller (standaard: 127.0.0.1)", "fr": "L'adresse IP de l'UniFi-Contrôleur (par défaut: 127.0.0.1)", "it": "L'indirizzo IP di UniFi Controller (default: 127.0.0.1)", "es": "Dirección IP de UniFi-Controlador (por defecto: 127.0.0.1)", "pl": "Adres IP Унифи-kontroler (domyślnie: 127.0.0.1)", "zh-cn": "IP地址的统一控制器(default:127.0.0.1)"},
    "controller_password": {                         "en": "UniFi-Controller Password",                       "de": "UniFi-Controller-Passwort",                       "ru": "Пароль Унифи-Контроллер ",                        "pt": "UniFi-Controlador De Senha",                      "nl": "UniFi-Controller Wachtwoord",                     "fr": "UniFi-Contrôleur De Mot De Passe",                "it": "UniFi-Controller Password",                       "es": "UniFi-Controlador De Contraseña",                 "pl": "Hasło Унифи-Kontroler ",                          "zh-cn": "统一控制器的密码"},
    "controller_password_info": {                    "en": "Password of UniFi-Controller",                    "de": "Kennwort der UniFi-Controller",                   "ru": "Пароль Унифи-контроллер",                         "pt": "Palavra-passe de UniFi-Controlador de",           "nl": "Wachtwoord van de UniFi-Controller",              "fr": "Mot de passe de l'UniFi-Contrôleur",              "it": "Password di UniFi Controller",                    "es": "Contraseña de UniFi-Controlador",                 "pl": "Hasło Унифи-kontroler",                           "zh-cn": "密码的统一控制器"},
    "controller_port": {                             "en": "UniFi-Controller Port",                           "de": "UniFi-Controller-Port",                           "ru": "Унифи-Контроллер Порт",                           "pt": "UniFi-Porta Do Controlador",                      "nl": "UniFi-Controller Poort",                          "fr": "UniFi-Contrôleur De Port",                        "it": "UniFi-Porta Del Controller",                      "es": "UniFi-Controlador De Puerto",                     "pl": "Унифи-Kontroler Portu",                           "zh-cn": "统一控制器的端口"},
    "controller_port_info": {                        "en": "Port of UniFi-Controller (default: 8443)",        "de": "Hafen von UniFi-Controller (Standard: 8443)",     "ru": "Порт Унифи-контроллер (по умолчанию: 8443)",      "pt": "Porta de UniFi-Controlador (predefinição: 8443)", "nl": "De haven van UniFi-Controller (standaard: 8443)", "fr": "Port de UniFi-Contrôleur (par défaut: 8443)",     "it": "Porto di UniFi Controller (default: 8443)",       "es": "Puerto de UniFi-Controlador (por defecto: 8443)", "pl": "Port Унифи-kontroler (domyślnie: 8443)",          "zh-cn": "港口的统一控制器(default:8443)"},
    "controller_username": {                         "en": "UniFi-Controller Username",                       "de": "UniFi-Controller Username",                       "ru": "Унифи-Контроллер Логин",                          "pt": "UniFi-Controlador Nome De Usuário",               "nl": "UniFi-Controller Gebruikersnaam",                 "fr": "UniFi-Contrôleur De Nom D'Utilisateur",           "it": "UniFi-Controller Username",                       "es": "UniFi-Controlador De Nombre De Usuario",          "pl": "Унифи-Kontroler Login",                           "zh-cn": "统一控制的用户名"},
    "controller_username_info": {                    "en": "Username of UniFi-Controller (default: admin)",   "de": "Benutzername der UniFi-Controller (Standard: admin)", "ru": "Имя Унифи-контроллер (по умолчанию: admin)",      "pt": "Nome do UniFi-Controlador (predefinição: admin)", "nl": "Gebruikersnaam van de UniFi-Controller (fabrieksinstelling: admin)", "fr": "Nom d'utilisateur de l'UniFi-Contrôleur (par défaut: admin)", "it": "Nome dell'UniFi-Controller (default: admin)",     "es": "Nombre de usuario de UniFi-Controlador (predeterminado: admin)", "pl": "Nazwa Унифи-kontroler (domyślnie: admin)",        "zh-cn": "用户名的统一控制器(default:admin)"},
    "unifi adapter settings": {                      "en": "UniFi Adapter Settings",                          "de": "UniFi-Adapter-Einstellungen",                     "ru": "Параметров Адаптера Унифи ",                      "pt": "UniFi As Configurações Do Adaptador",             "nl": "UniFi-Adapter Instellingen",                      "fr": "UniFi Les Paramètres De La Carte",                "it": "UniFi Impostazioni Della Scheda Di",              "es": "UniFi Configuración Del Adaptador",               "pl": "Ustawienia Karty Sieciowej Унифи ",               "zh-cn": "该设置适配器"},
    "update_interval": {                             "en": "Update Interval",                                 "de": "Update-Intervall",                                "ru": "Интервал Обновления",                             "pt": "Intervalo De Atualização",                        "nl": "Update-Interval",                                 "fr": "Intervalle De Mise À Jour",                       "it": "Intervallo Di Aggiornamento",                     "es": "Intervalo De Actualización",                      "pl": "Interwał Aktualizacji",                           "zh-cn": "更新的时间间隔"},
    "update_interval_info": {                        "en": "Interval in seconds to check for updates (default: 60 sec)", "de": "Intervall in Sekunden an, nach updates zu suchen (default: 60 sec)", "ru": "Интервал в секундах для проверки для обновления (по умолчанию: 60 секунд)", "pt": "O intervalo, em segundos, para verificar se há atualizações (padrão: 60 s)", "nl": "Interval in seconden ingedrukt om te controleren op updates (standaard: 60 seconden)", "fr": "Intervalle (en secondes) pour vérifier les mises à jour (par défaut: 60 secondes)", "it": "Intervallo di tempo in secondi per controllare la disponibilità di aggiornamenti (default: 60 sec)", "es": "Intervalo en segundos para comprobar si hay actualizaciones (por defecto: 60 seg.)", "pl": "Interwał w sekundach, aby sprawdzić, czy aktualizacje (domyślnie: 60 sekund)", "zh-cn": "间隔几秒钟内检查更新的(默认60秒)"},
};